<script lang="ts">
  export let report: any;
  export let userProfile: any;
  
  // Normalize report data: prefer nested AI payload if present, else use top-level fields
  const reportData = report?.report || report || {};
  
  // Core values with robust fallbacks
  $: score = (reportData?.score ?? report?.esgScore ?? 0) as number;
  $: summary = (reportData?.summary ?? '') as string;
  $: suggestions = (reportData?.suggestions ?? report?.recommendations ?? []) as string[];
  $: environmentalScore = (reportData?.environmentalScore ?? Math.floor(score * 0.4) ?? 0) as number;
  $: socialScore = (reportData?.socialScore ?? Math.floor(score * 0.3) ?? 0) as number;
  $: governanceScore = (reportData?.governanceScore ?? Math.floor(score * 0.3) ?? 0) as number;
  $: benchmarkPosition = (reportData?.benchmarkPosition ?? getBenchmarkFromScore(score)) as string;
  $: riskLevel = (reportData?.riskLevel ?? getRiskFromScore(score)) as string;
  $: quickWins = (reportData?.quickWins ?? []) as string[];
  $: longTermGoals = (reportData?.longTermGoals ?? []) as string[];
  $: complianceGaps = (reportData?.complianceGaps ?? []) as string[];
  
  function getBenchmarkFromScore(score: number): string {
    if (score >= 80) return "Leading";
    if (score >= 65) return "Above Average";
    if (score >= 45) return "Average";
    return "Below Average";
  }
  
  function getRiskFromScore(score: number): string {
    if (score >= 70) return "Low";
    if (score >= 50) return "Medium";
    return "High";
  }
  
  function getScoreColor(score: number): string {
    if (score >= 80) return "#2A9D8F"; // Green
    if (score >= 60) return "#E9C46A"; // Yellow
    if (score >= 40) return "#F4A261"; // Orange
    return "#E76F51"; // Red
  }
  
  function getRiskColor(risk: string): string {
    switch (risk) {
      case "Low": return "#2A9D8F";
      case "Medium": return "#E9C46A";
      case "High": return "#E76F51";
      default: return "#6C757D";
    }
  }
  
  function formatDate(timestamp: any): string {
    if (!timestamp) return "Unknown";
    const date = timestamp.seconds ? new Date(timestamp.seconds * 1000) : new Date(timestamp);
    return date.toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
  }
  
  const downloadReport = () => {
    // Create a comprehensive report document
    const reportContent = `
YAHMI ESG SUSTAINABILITY REPORT
Generated: ${formatDate(report.generatedAt)}
Company: ${userProfile?.companyName || 'Your Organization'}
Industry: ${userProfile?.industry || 'Not specified'}

EXECUTIVE SUMMARY
Overall ESG Score: ${report.score}/100
Benchmark Position: ${benchmarkPosition}
Risk Level: ${riskLevel}

${report.summary}

DETAILED SCORES
Environmental: ${environmentalScore}/100
Social: ${socialScore}/100
Governance: ${governanceScore}/100

RECOMMENDATIONS
${report.suggestions?.map((s, i) => `${i + 1}. ${s}`).join('\n') || 'No specific recommendations available.'}

${report.quickWins ? `
QUICK WINS (High Impact, Low Effort)
${report.quickWins.map((w, i) => `${i + 1}. ${w}`).join('\n')}
` : ''}

${report.longTermGoals ? `
LONG-TERM STRATEGIC GOALS
${report.longTermGoals.map((g, i) => `${i + 1}. ${g}`).join('\n')}
` : ''}

${report.complianceGaps ? `
COMPLIANCE GAPS TO ADDRESS
${report.complianceGaps.map((g, i) => `${i + 1}. ${g}`).join('\n')}
` : ''}

This report was generated by Yahmi AI-powered sustainability assessment platform.
For more information, visit: https://yahmi.ai
    `.trim();
    
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Yahmi_ESG_Report_${formatDate(report.generatedAt).replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };
</script>

<div class="business-esg-report">
  <!-- Report Header -->
  <div class="report-header glass-card">
    <div class="header-content">
      <div class="company-info">
        <h1>ESG Sustainability Report</h1>
        <div class="company-details">
          <span class="company-name">{userProfile?.companyName || 'Your Organization'}</span>
          <span class="industry-tag">{userProfile?.industry || 'Industry Not Specified'}</span>
        </div>
        <div class="report-meta">
          <span class="generated-date">Generated: {formatDate(report.generatedAt)}</span>
          <span class="report-id">Report ID: {report.id?.slice(-8) || 'N/A'}</span>
        </div>
      </div>
      
      <div class="overall-score">
        <div class="score-circle" style="border-color: {getScoreColor(report.score)}">
          <span class="score-number" style="color: {getScoreColor(report.score)}">{report.score}</span>
          <span class="score-label">ESG Score</span>
        </div>
        <div class="benchmark-info">
          <div class="benchmark-position" style="color: {getScoreColor(report.score)}">
            {benchmarkPosition}
          </div>
          <div class="risk-level" style="color: {getRiskColor(riskLevel)}">
            Risk: {riskLevel}
          </div>
        </div>
      </div>
    </div>
    
    <div class="header-actions">
      <button class="btn btn-primary" on:click={downloadReport}>
        📄 Download Report
      </button>
      <button class="btn btn-glass" on:click={() => window.print()}>
        🖨️ Print Report
      </button>
    </div>
  </div>

  <!-- Executive Summary -->
  <div class="executive-summary glass-card">
    <h2>Executive Summary</h2>
    <p class="summary-text">{summary}</p>
  </div>

  <!-- ESG Scores Breakdown -->
  <div class="esg-scores glass-card">
    <h2>ESG Performance Breakdown</h2>
    <div class="scores-grid">
      <div class="score-item environmental">
        <div class="score-icon">🌱</div>
        <div class="score-details">
          <h3>Environmental</h3>
          <div class="score-bar">
            <div class="score-fill" style="width: {environmentalScore}%; background-color: {getScoreColor(environmentalScore)}"></div>
          </div>
          <span class="score-value">{environmentalScore}/100</span>
        </div>
      </div>
      
      <div class="score-item social">
        <div class="score-icon">👥</div>
        <div class="score-details">
          <h3>Social</h3>
          <div class="score-bar">
            <div class="score-fill" style="width: {socialScore}%; background-color: {getScoreColor(socialScore)}"></div>
          </div>
          <span class="score-value">{socialScore}/100</span>
        </div>
      </div>
      
      <div class="score-item governance">
        <div class="score-icon">⚖️</div>
        <div class="score-details">
          <h3>Governance</h3>
          <div class="score-bar">
            <div class="score-fill" style="width: {governanceScore}%; background-color: {getScoreColor(governanceScore)}"></div>
          </div>
          <span class="score-value">{governanceScore}/100</span>
        </div>
      </div>
    </div>
  </div>

  <!-- Quick Wins Section -->
  {#if report.quickWins && report.quickWins.length > 0}
    <div class="quick-wins glass-card">
      <h2>🚀 Quick Wins (High Impact, Low Effort)</h2>
      <div class="wins-grid">
        {#each quickWins as win, index}
          <div class="win-item">
            <div class="win-number">{index + 1}</div>
            <div class="win-text">{win}</div>
          </div>
        {/each}
      </div>
    </div>
  {/if}

  <!-- Strategic Recommendations -->
  <div class="recommendations glass-card">
    <h2>📈 Strategic Recommendations</h2>
    <div class="recommendations-list">
      {#each suggestions || [] as suggestion, index}
        <div class="recommendation-item">
          <div class="recommendation-number">{index + 1}</div>
          <div class="recommendation-content">
            <p>{suggestion}</p>
          </div>
        </div>
      {/each}
    </div>
  </div>

  <!-- Long-term Goals -->
  {#if report.longTermGoals && report.longTermGoals.length > 0}
    <div class="long-term-goals glass-card">
      <h2>🎯 Long-term Strategic Goals</h2>
      <div class="goals-list">
        {#each report.longTermGoals as goal, index}
          <div class="goal-item">
            <div class="goal-icon">🎯</div>
            <div class="goal-text">{goal}</div>
          </div>
        {/each}
      </div>
    </div>
  {/if}

  <!-- Compliance Gaps -->
  {#if report.complianceGaps && report.complianceGaps.length > 0}
    <div class="compliance-gaps glass-card">
      <h2>⚠️ Compliance Gaps to Address</h2>
      <div class="gaps-list">
        {#each report.complianceGaps as gap, index}
          <div class="gap-item">
            <div class="gap-icon">⚠️</div>
            <div class="gap-text">{gap}</div>
          </div>
        {/each}
      </div>
    </div>
  {/if}

  <!-- Next Steps -->
  <div class="next-steps glass-card">
    <h2>🔄 Next Steps</h2>
    <div class="steps-content">
      <div class="step-item">
        <div class="step-icon">📊</div>
        <div class="step-content">
          <h3>Track Progress</h3>
          <p>Implement KPIs and regular monitoring for the recommended initiatives</p>
        </div>
      </div>
      
      <div class="step-item">
        <div class="step-icon">👥</div>
        <div class="step-content">
          <h3>Engage Stakeholders</h3>
          <p>Share this report with key stakeholders and integrate feedback into your strategy</p>
        </div>
      </div>
      
      <div class="step-item">
        <div class="step-icon">🔄</div>
        <div class="step-content">
          <h3>Schedule Reassessment</h3>
          <p>Plan your next sustainability assessment in 6-12 months to track improvements</p>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .business-esg-report {
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
    gap: 30px;
    display: flex;
    flex-direction: column;
  }

  .report-header {
    padding: 40px;
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    flex-wrap: wrap;
    gap: 30px;
  }

  .header-content {
    display: flex;
    gap: 40px;
    align-items: flex-start;
    flex: 1;
  }

  .company-info h1 {
    font-size: 2.5rem;
    font-weight: 700;
    color: var(--primary-white);
    margin-bottom: 15px;
  }

  .company-details {
    display: flex;
    gap: 15px;
    align-items: center;
    margin-bottom: 10px;
  }

  .company-name {
    font-size: 1.2rem;
    font-weight: 600;
    color: var(--primary-green);
  }

  .industry-tag {
    background: rgba(42, 157, 143, 0.2);
    color: var(--primary-green);
    padding: 4px 12px;
    border-radius: 20px;
    font-size: 0.9rem;
    font-weight: 500;
  }

  .report-meta {
    display: flex;
    gap: 20px;
    font-size: 0.9rem;
    opacity: 0.8;
  }

  .overall-score {
    display: flex;
    align-items: center;
    gap: 20px;
  }

  .score-circle {
    width: 120px;
    height: 120px;
    border: 4px solid;
    border-radius: 50%;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    background: rgba(255, 255, 255, 0.05);
  }

  .score-number {
    font-size: 2.5rem;
    font-weight: 700;
  }

  .score-label {
    font-size: 0.9rem;
    opacity: 0.8;
    color: var(--primary-white);
  }

  .benchmark-info {
    text-align: center;
  }

  .benchmark-position {
    font-size: 1.2rem;
    font-weight: 600;
    margin-bottom: 5px;
  }

  .risk-level {
    font-size: 1rem;
    font-weight: 500;
  }

  .header-actions {
    display: flex;
    gap: 15px;
    flex-wrap: wrap;
  }

  .executive-summary {
    padding: 30px;
  }

  .executive-summary h2 {
    font-size: 1.8rem;
    font-weight: 600;
    color: var(--primary-white);
    margin-bottom: 20px;
  }

  .summary-text {
    font-size: 1.1rem;
    line-height: 1.6;
    color: var(--primary-white);
    opacity: 0.9;
  }

  .esg-scores {
    padding: 30px;
  }

  .esg-scores h2 {
    font-size: 1.8rem;
    font-weight: 600;
    color: var(--primary-white);
    margin-bottom: 30px;
  }

  .scores-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 25px;
  }

  .score-item {
    display: flex;
    align-items: center;
    gap: 20px;
    padding: 20px;
    background: rgba(255, 255, 255, 0.05);
    border-radius: 12px;
    border: 1px solid rgba(255, 255, 255, 0.1);
  }

  .score-icon {
    font-size: 2.5rem;
  }

  .score-details {
    flex: 1;
  }

  .score-details h3 {
    font-size: 1.2rem;
    font-weight: 600;
    color: var(--primary-white);
    margin-bottom: 10px;
  }

  .score-bar {
    width: 100%;
    height: 8px;
    background: rgba(255, 255, 255, 0.1);
    border-radius: 4px;
    overflow: hidden;
    margin-bottom: 8px;
  }

  .score-fill {
    height: 100%;
    border-radius: 4px;
    transition: width 0.3s ease;
  }

  .score-value {
    font-size: 1.1rem;
    font-weight: 600;
    color: var(--primary-white);
  }

  .quick-wins {
    padding: 30px;
  }

  .quick-wins h2 {
    font-size: 1.8rem;
    font-weight: 600;
    color: var(--primary-white);
    margin-bottom: 25px;
  }

  .wins-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 20px;
  }

  .win-item {
    display: flex;
    gap: 15px;
    padding: 20px;
    background: rgba(42, 157, 143, 0.1);
    border: 1px solid rgba(42, 157, 143, 0.3);
    border-radius: 12px;
  }

  .win-number {
    width: 30px;
    height: 30px;
    background: var(--primary-green);
    color: white;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: 600;
    flex-shrink: 0;
  }

  .win-text {
    flex: 1;
    color: var(--primary-white);
    line-height: 1.5;
  }

  .recommendations {
    padding: 30px;
  }

  .recommendations h2 {
    font-size: 1.8rem;
    font-weight: 600;
    color: var(--primary-white);
    margin-bottom: 25px;
  }

  .recommendations-list {
    display: flex;
    flex-direction: column;
    gap: 20px;
  }

  .recommendation-item {
    display: flex;
    gap: 20px;
    padding: 25px;
    background: rgba(255, 255, 255, 0.05);
    border-radius: 12px;
    border: 1px solid rgba(255, 255, 255, 0.1);
  }

  .recommendation-number {
    width: 40px;
    height: 40px;
    background: var(--primary-green);
    color: white;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: 600;
    font-size: 1.1rem;
    flex-shrink: 0;
  }

  .recommendation-content p {
    color: var(--primary-white);
    line-height: 1.6;
    margin: 0;
  }

  .long-term-goals, .compliance-gaps {
    padding: 30px;
  }

  .long-term-goals h2, .compliance-gaps h2 {
    font-size: 1.8rem;
    font-weight: 600;
    color: var(--primary-white);
    margin-bottom: 25px;
  }

  .goals-list, .gaps-list {
    display: flex;
    flex-direction: column;
    gap: 15px;
  }

  .goal-item, .gap-item {
    display: flex;
    gap: 15px;
    align-items: flex-start;
    padding: 20px;
    background: rgba(255, 255, 255, 0.05);
    border-radius: 12px;
    border: 1px solid rgba(255, 255, 255, 0.1);
  }

  .goal-icon, .gap-icon {
    font-size: 1.5rem;
    flex-shrink: 0;
  }

  .goal-text, .gap-text {
    flex: 1;
    color: var(--primary-white);
    line-height: 1.5;
  }

  .next-steps {
    padding: 30px;
  }

  .next-steps h2 {
    font-size: 1.8rem;
    font-weight: 600;
    color: var(--primary-white);
    margin-bottom: 25px;
  }

  .steps-content {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 25px;
  }

  .step-item {
    display: flex;
    gap: 20px;
    padding: 25px;
    background: rgba(255, 255, 255, 0.05);
    border-radius: 12px;
    border: 1px solid rgba(255, 255, 255, 0.1);
  }

  .step-icon {
    font-size: 2rem;
    flex-shrink: 0;
  }

  .step-content h3 {
    font-size: 1.2rem;
    font-weight: 600;
    color: var(--primary-white);
    margin-bottom: 8px;
  }

  .step-content p {
    color: var(--primary-white);
    opacity: 0.8;
    line-height: 1.5;
    margin: 0;
  }

  @media (max-width: 768px) {
    .business-esg-report {
      padding: 15px;
    }

    .report-header {
      padding: 25px;
      flex-direction: column;
      align-items: stretch;
    }

    .header-content {
      flex-direction: column;
      gap: 20px;
    }

    .overall-score {
      justify-content: center;
    }

    .company-info h1 {
      font-size: 2rem;
    }

    .scores-grid {
      grid-template-columns: 1fr;
    }

    .wins-grid {
      grid-template-columns: 1fr;
    }

    .steps-content {
      grid-template-columns: 1fr;
    }
  }
</style>